version: '3.5'

volumes:
  easy-evs-data:
    name: easy-evs-data
    driver: local
    
services:
  eventstore.db:
    image: eventstore/eventstore:21.6.0-buster-slim
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=TRUE
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - easy-evs-data:/var/lib/eventstore
