name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: run minver
      id: version
      uses: thefringeninja/action-minver@2.0.0-preview1
      with:
        # Optional. Specifies which part of the version to auto-increment.
        auto-increment: patch
        # Optional. Sets custom build metadata for your semantic version.
        build-metadata: ${{ github.sha }}
        # Optional. Specifies the default pre-release phase.
        default-pre-release-phase: preview
        # Optional. Specifies the minimum version to use when no tags exist.
        minimum-major-minor: 2.0.0
        # Optional. Specifies the prefix of the tags
        tag-prefix: v
        # Optional. Specifies the log level.
        verbosity: trace
    - name: output
      run: |
        echo ${{ steps.version.outputs.version }}
